spring.application.name=JSON

spring.datasource.url=jdbc:h2:file:./data/jsondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=true

app.jwt.secret=super-long-dev-secret-change-me-please-1234567890

spring.security.debug=true
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

logging.file.name=security-debug.log
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n